[Tue Nov 07 21:38:32.546002 2017] [cgid:error] [pid 22092:tid 140289998857408] (13)Permission denied: AH01241: exec of '/home/2017/y2017g48/apache/cgi-bin/dump.pl' failed
[Tue Nov 07 21:38:32.546940 2017] [cgid:error] [pid 21898:tid 140289746372352] [client 10.0.27.1:60201] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
[Tue Nov 07 21:38:37.996390 2017] [cgid:error] [pid 22093:tid 140289998857408] (13)Permission denied: AH01241: exec of '/home/2017/y2017g48/apache/cgi-bin/dump.pl' failed
[Tue Nov 07 21:38:37.997139 2017] [cgid:error] [pid 21896:tid 140289746372352] [client 10.0.27.1:60203] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
	(Missing semicolon on previous line?)
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 16, near "$q"
	(Missing semicolon on previous line?)
syntax error at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
Execution of /home/2017/y2017g48/apache/cgi-bin/dump.pl aborted due to compilation errors.
[Tue Nov 07 21:43:39.599008 2017] [cgid:error] [pid 21894:tid 140289704408832] [client 10.0.27.1:60461] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
	(Missing semicolon on previous line?)
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 16, near "$q"
	(Missing semicolon on previous line?)
syntax error at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
Execution of /home/2017/y2017g48/apache/cgi-bin/dump.pl aborted due to compilation errors.
[Tue Nov 07 21:43:39.772768 2017] [cgid:error] [pid 21896:tid 140289737979648] [client 10.0.27.1:60462] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
	(Missing semicolon on previous line?)
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 16, near "$q"
	(Missing semicolon on previous line?)
syntax error at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
Execution of /home/2017/y2017g48/apache/cgi-bin/dump.pl aborted due to compilation errors.
[Tue Nov 07 21:43:39.935894 2017] [cgid:error] [pid 21898:tid 140289704408832] [client 10.0.27.1:60463] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
	(Missing semicolon on previous line?)
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 16, near "$q"
	(Missing semicolon on previous line?)
syntax error at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
Execution of /home/2017/y2017g48/apache/cgi-bin/dump.pl aborted due to compilation errors.
[Tue Nov 07 21:43:40.093114 2017] [cgid:error] [pid 21896:tid 140289729586944] [client 10.0.27.1:60464] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
	(Missing semicolon on previous line?)
Scalar found where operator expected at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 16, near "$q"
	(Missing semicolon on previous line?)
syntax error at /home/2017/y2017g48/apache/cgi-bin/dump.pl line 11, near "$q"
Execution of /home/2017/y2017g48/apache/cgi-bin/dump.pl aborted due to compilation errors.
[Tue Nov 07 21:43:46.220366 2017] [cgid:error] [pid 21898:tid 140289670838016] [client 10.0.27.1:60465] End of script output before headers: dump.pl, referer: http://162.105.146.180:8048/example/homework6_5.html
[Thu Nov 30 14:23:36.465667 2017] [mpm_event:notice] [pid 21892:tid 140289998857408] AH00491: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 14:23:40.555160 2017] [mpm_event:notice] [pid 14550:tid 140314458985664] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 configured -- resuming normal operations
[Thu Nov 30 14:23:40.555303 2017] [core:notice] [pid 14550:tid 140314458985664] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 19:48:48.389812 2017] [mpm_event:notice] [pid 14550:tid 140314458985664] AH00491: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 19:48:49.959629 2017] [mpm_event:notice] [pid 16540:tid 139698448319680] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
[Thu Nov 30 19:48:49.959767 2017] [core:notice] [pid 16540:tid 139698448319680] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 19:48:52.639950 2017] [wsgi:error] [pid 16543:tid 139698319177472] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:53.009575 2017] [wsgi:error] [pid 16543:tid 139698240485120] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:53.210955 2017] [wsgi:error] [pid 16543:tid 139698232092416] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:54.110627 2017] [wsgi:error] [pid 16543:tid 139698223699712] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:54.838332 2017] [wsgi:error] [pid 16543:tid 139698215307008] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:55.069584 2017] [wsgi:error] [pid 16543:tid 139698206914304] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:55.933212 2017] [wsgi:error] [pid 16543:tid 139698198521600] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:57.109680 2017] [wsgi:error] [pid 16543:tid 139698190128896] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:57.305859 2017] [wsgi:error] [pid 16543:tid 139698181736192] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:48:57.482054 2017] [wsgi:error] [pid 16543:tid 139698173343488] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:01.883798 2017] [wsgi:error] [pid 16543:tid 139698164950784] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:02.131366 2017] [wsgi:error] [pid 16543:tid 139698156558080] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:02.286991 2017] [wsgi:error] [pid 16543:tid 139698148165376] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:02.468263 2017] [wsgi:error] [pid 16543:tid 139698139772672] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:02.639813 2017] [wsgi:error] [pid 16543:tid 139698131379968] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:02.797234 2017] [wsgi:error] [pid 16543:tid 139698122987264] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:02.966343 2017] [wsgi:error] [pid 16543:tid 139698114594560] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:03.137818 2017] [wsgi:error] [pid 16543:tid 139698106201856] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:03.303672 2017] [wsgi:error] [pid 16543:tid 139698097809152] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:03.485418 2017] [wsgi:error] [pid 16543:tid 139698089416448] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:07.757333 2017] [wsgi:error] [pid 16543:tid 139698081023744] [client 10.128.202.138:58684] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:49:44.049397 2017] [core:warn] [pid 16540:tid 139698448319680] AH00045: child process 16542 still did not exit, sending a SIGTERM
[Thu Nov 30 19:49:46.015817 2017] [core:warn] [pid 16540:tid 139698448319680] AH00045: child process 16542 still did not exit, sending a SIGTERM
[Thu Nov 30 19:49:48.018223 2017] [core:warn] [pid 16540:tid 139698448319680] AH00045: child process 16542 still did not exit, sending a SIGTERM
[Thu Nov 30 19:49:50.019935 2017] [core:error] [pid 16540:tid 139698448319680] AH00046: child process 16542 still did not exit, sending a SIGKILL
[Thu Nov 30 19:49:51.021325 2017] [mpm_event:notice] [pid 16540:tid 139698448319680] AH00491: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 19:50:02.105606 2017] [mpm_event:notice] [pid 16703:tid 139703440454848] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
[Thu Nov 30 19:50:02.105765 2017] [core:notice] [pid 16703:tid 139703440454848] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 19:50:08.863716 2017] [wsgi:error] [pid 16705:tid 139703311312640] [client 10.128.202.138:58728] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:09.497374 2017] [wsgi:error] [pid 16705:tid 139703294510848] [client 10.128.202.138:58728] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:09.713846 2017] [wsgi:error] [pid 16705:tid 139703302911744] [client 10.128.202.138:58728] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:09.901116 2017] [wsgi:error] [pid 16705:tid 139703286109952] [client 10.128.202.138:58728] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:10.121715 2017] [wsgi:error] [pid 16705:tid 139703206541056] [client 10.128.202.138:58728] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:34.966217 2017] [mpm_event:notice] [pid 16703:tid 139703440454848] AH00491: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 19:50:39.846934 2017] [mpm_event:notice] [pid 16834:tid 140153833862336] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
[Thu Nov 30 19:50:39.847064 2017] [core:notice] [pid 16834:tid 140153833862336] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 19:50:54.277148 2017] [mpm_event:notice] [pid 16834:tid 140153833862336] AH00491: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 19:50:55.107844 2017] [mpm_event:notice] [pid 16926:tid 140496731239616] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
[Thu Nov 30 19:50:55.107982 2017] [core:notice] [pid 16926:tid 140496731239616] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 19:50:57.556657 2017] [wsgi:error] [pid 16929:tid 140496593696512] [client 10.128.202.138:58746] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:57.917101 2017] [wsgi:error] [pid 16929:tid 140496602097408] [client 10.128.202.138:58746] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:58.072581 2017] [wsgi:error] [pid 16929:tid 140496585295616] [client 10.128.202.138:58746] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:58.250147 2017] [wsgi:error] [pid 16929:tid 140496576894720] [client 10.128.202.138:58746] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:50:58.394999 2017] [wsgi:error] [pid 16929:tid 140496500422400] [client 10.128.202.138:58746] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:55:18.363611 2017] [wsgi:error] [pid 16929:tid 140496483636992] [client 10.128.202.138:58814] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:55:18.544382 2017] [wsgi:error] [pid 16929:tid 140496475244288] [client 10.128.202.138:58814] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 19:55:18.710459 2017] [wsgi:error] [pid 16929:tid 140496466851584] [client 10.128.202.138:58814] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 20:02:40.932289 2017] [wsgi:error] [pid 16928:tid 140496602097408] [client 10.128.202.138:59184] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 20:02:41.324123 2017] [wsgi:error] [pid 16928:tid 140496585295616] [client 10.128.202.138:59184] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 20:02:42.044749 2017] [wsgi:error] [pid 16928:tid 140496576894720] [client 10.128.202.138:59184] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 20:02:42.211142 2017] [wsgi:error] [pid 16928:tid 140496500422400] [client 10.128.202.138:59184] Target WSGI script not found or unable to stat: /django
[Thu Nov 30 20:02:58.423321 2017] [mpm_event:notice] [pid 16926:tid 140496731239616] AH00491: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 20:03:01.088880 2017] [mpm_event:notice] [pid 18162:tid 140070891574464] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
[Thu Nov 30 20:03:01.089010 2017] [core:notice] [pid 18162:tid 140070891574464] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 21:16:15.148126 2017] [mpm_event:notice] [pid 18162:tid 140070891574464] AH00491: caught SIGTERM, shutting down
[Thu Nov 30 21:16:17.437078 2017] [proxy_balancer:emerg] [pid 18979:tid 139718364624064] AH01177: Failed to lookup provider 'shm' for 'slotmem': is mod_slotmem_shm loaded??
[Thu Nov 30 21:16:17.437251 2017] [:emerg] [pid 18979:tid 139718364624064] AH00020: Configuration Failed, exiting
[Thu Nov 30 21:16:35.087378 2017] [proxy_balancer:emerg] [pid 18983:tid 140673334666432] AH01177: Failed to lookup provider 'shm' for 'slotmem': is mod_slotmem_shm loaded??
[Thu Nov 30 21:16:35.087556 2017] [:emerg] [pid 18983:tid 140673334666432] AH00020: Configuration Failed, exiting
[Thu Nov 30 21:16:46.673135 2017] [proxy_balancer:emerg] [pid 18990:tid 139843447080128] AH01177: Failed to lookup provider 'shm' for 'slotmem': is mod_slotmem_shm loaded??
[Thu Nov 30 21:16:46.673321 2017] [:emerg] [pid 18990:tid 139843447080128] AH00020: Configuration Failed, exiting
[Thu Nov 30 21:17:38.845197 2017] [proxy_balancer:emerg] [pid 18997:tid 139806761497792] AH01177: Failed to lookup provider 'shm' for 'slotmem': is mod_slotmem_shm loaded??
[Thu Nov 30 21:17:38.845368 2017] [:emerg] [pid 18997:tid 139806761497792] AH00020: Configuration Failed, exiting
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 21:18:22.006917 2017] [proxy_hcheck:crit] [pid 19001:tid 140192210580672] AH03262: mod_watchdog is required
[Thu Nov 30 21:18:22.006989 2017] [:emerg] [pid 19001:tid 140192210580672] AH00020: Configuration Failed, exiting
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_oci.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_odbc.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll' - /home/2017/y2017g48/php/lib/php/extensions/no-debug-zts-20131226/php_pdo_sqlite.dll: cannot open shared object file: No such file or directory in Unknown on line 0
[Thu Nov 30 21:18:47.516687 2017] [mpm_event:notice] [pid 19006:tid 139934338081984] AH00489: Apache/2.4.27 (Unix) PHP/5.6.31 mod_wsgi/4.5.22 Python/2.7 configured -- resuming normal operations
[Thu Nov 30 21:18:47.516809 2017] [core:notice] [pid 19006:tid 139934338081984] AH00094: Command line: '/home/2017/y2017g48/apache/bin/httpd'
[Thu Nov 30 21:19:26.801155 2017] [wsgi:error] [pid 19009:tid 139934187230976] [client 10.128.202.138:48112] mod_wsgi (pid=19009): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:19:26.801245 2017] [wsgi:error] [pid 19009:tid 139934187230976] [client 10.128.202.138:48112] mod_wsgi (pid=19009): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:19:26.801276 2017] [wsgi:error] [pid 19009:tid 139934187230976] [client 10.128.202.138:48112] Traceback (most recent call last):
[Thu Nov 30 21:19:26.801312 2017] [wsgi:error] [pid 19009:tid 139934187230976] [client 10.128.202.138:48112]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:19:26.801395 2017] [wsgi:error] [pid 19009:tid 139934187230976] [client 10.128.202.138:48112]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:19:26.801428 2017] [wsgi:error] [pid 19009:tid 139934187230976] [client 10.128.202.138:48112] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:19:26.820396 2017] [wsgi:error] [pid 19009:tid 139934178830080] [client 10.128.202.138:48114] mod_wsgi (pid=19009): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:26.820437 2017] [wsgi:error] [pid 19009:tid 139934178830080] [client 10.128.202.138:48114] mod_wsgi (pid=19009): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:26.820480 2017] [wsgi:error] [pid 19009:tid 139934178830080] [client 10.128.202.138:48114] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:26.820549 2017] [wsgi:error] [pid 19009:tid 139934178830080] [client 10.128.202.138:48114]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:26.820617 2017] [wsgi:error] [pid 19009:tid 139934178830080] [client 10.128.202.138:48114]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:26.820657 2017] [wsgi:error] [pid 19009:tid 139934178830080] [client 10.128.202.138:48114] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:27.900280 2017] [wsgi:error] [pid 19010:tid 139934187230976] [client 10.128.202.138:48116] mod_wsgi (pid=19010): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:19:27.900347 2017] [wsgi:error] [pid 19010:tid 139934187230976] [client 10.128.202.138:48116] mod_wsgi (pid=19010): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:19:27.900377 2017] [wsgi:error] [pid 19010:tid 139934187230976] [client 10.128.202.138:48116] Traceback (most recent call last):
[Thu Nov 30 21:19:27.900410 2017] [wsgi:error] [pid 19010:tid 139934187230976] [client 10.128.202.138:48116]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:19:27.900492 2017] [wsgi:error] [pid 19010:tid 139934187230976] [client 10.128.202.138:48116]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:19:27.900525 2017] [wsgi:error] [pid 19010:tid 139934187230976] [client 10.128.202.138:48116] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:19:27.934619 2017] [wsgi:error] [pid 19008:tid 139934187230976] [client 10.128.202.138:48118] mod_wsgi (pid=19008): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:27.934688 2017] [wsgi:error] [pid 19008:tid 139934187230976] [client 10.128.202.138:48118] mod_wsgi (pid=19008): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:27.934716 2017] [wsgi:error] [pid 19008:tid 139934187230976] [client 10.128.202.138:48118] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:27.934750 2017] [wsgi:error] [pid 19008:tid 139934187230976] [client 10.128.202.138:48118]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:27.934832 2017] [wsgi:error] [pid 19008:tid 139934187230976] [client 10.128.202.138:48118]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:27.934864 2017] [wsgi:error] [pid 19008:tid 139934187230976] [client 10.128.202.138:48118] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:34.361735 2017] [wsgi:error] [pid 19009:tid 139934052640512] [client 10.128.202.138:48120] mod_wsgi (pid=19009): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:19:34.361778 2017] [wsgi:error] [pid 19009:tid 139934052640512] [client 10.128.202.138:48120] mod_wsgi (pid=19009): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:19:34.361812 2017] [wsgi:error] [pid 19009:tid 139934052640512] [client 10.128.202.138:48120] Traceback (most recent call last):
[Thu Nov 30 21:19:34.361848 2017] [wsgi:error] [pid 19009:tid 139934052640512] [client 10.128.202.138:48120]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:19:34.361900 2017] [wsgi:error] [pid 19009:tid 139934052640512] [client 10.128.202.138:48120]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:19:34.361943 2017] [wsgi:error] [pid 19009:tid 139934052640512] [client 10.128.202.138:48120] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:19:34.377239 2017] [wsgi:error] [pid 19010:tid 139934178830080] [client 10.128.202.138:48122] mod_wsgi (pid=19010): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:34.377280 2017] [wsgi:error] [pid 19010:tid 139934178830080] [client 10.128.202.138:48122] mod_wsgi (pid=19010): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:34.377318 2017] [wsgi:error] [pid 19010:tid 139934178830080] [client 10.128.202.138:48122] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:34.377359 2017] [wsgi:error] [pid 19010:tid 139934178830080] [client 10.128.202.138:48122]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:34.377422 2017] [wsgi:error] [pid 19010:tid 139934178830080] [client 10.128.202.138:48122]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:34.377461 2017] [wsgi:error] [pid 19010:tid 139934178830080] [client 10.128.202.138:48122] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:40.487153 2017] [wsgi:error] [pid 19008:tid 139934162028288] [client 10.128.202.138:48130] mod_wsgi (pid=19008): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:19:40.487203 2017] [wsgi:error] [pid 19008:tid 139934162028288] [client 10.128.202.138:48130] mod_wsgi (pid=19008): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:19:40.487242 2017] [wsgi:error] [pid 19008:tid 139934162028288] [client 10.128.202.138:48130] Traceback (most recent call last):
[Thu Nov 30 21:19:40.487285 2017] [wsgi:error] [pid 19008:tid 139934162028288] [client 10.128.202.138:48130]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:19:40.487347 2017] [wsgi:error] [pid 19008:tid 139934162028288] [client 10.128.202.138:48130]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:19:40.487387 2017] [wsgi:error] [pid 19008:tid 139934162028288] [client 10.128.202.138:48130] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:19:40.504173 2017] [wsgi:error] [pid 19008:tid 139934153627392] [client 10.128.202.138:48142] mod_wsgi (pid=19008): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:40.504240 2017] [wsgi:error] [pid 19008:tid 139934153627392] [client 10.128.202.138:48142] mod_wsgi (pid=19008): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:40.504273 2017] [wsgi:error] [pid 19008:tid 139934153627392] [client 10.128.202.138:48142] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:40.504314 2017] [wsgi:error] [pid 19008:tid 139934153627392] [client 10.128.202.138:48142]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:40.504360 2017] [wsgi:error] [pid 19008:tid 139934153627392] [client 10.128.202.138:48142]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:19:40.504389 2017] [wsgi:error] [pid 19008:tid 139934153627392] [client 10.128.202.138:48142] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:08.430594 2017] [wsgi:error] [pid 19009:tid 139934044247808] [client 10.128.202.138:48146] mod_wsgi (pid=19009): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:20:08.430732 2017] [wsgi:error] [pid 19009:tid 139934044247808] [client 10.128.202.138:48146] mod_wsgi (pid=19009): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:20:08.430777 2017] [wsgi:error] [pid 19009:tid 139934044247808] [client 10.128.202.138:48146] Traceback (most recent call last):
[Thu Nov 30 21:20:08.430819 2017] [wsgi:error] [pid 19009:tid 139934044247808] [client 10.128.202.138:48146]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:20:08.430883 2017] [wsgi:error] [pid 19009:tid 139934044247808] [client 10.128.202.138:48146]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:20:08.430921 2017] [wsgi:error] [pid 19009:tid 139934044247808] [client 10.128.202.138:48146] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:20:08.444399 2017] [wsgi:error] [pid 19008:tid 139934145226496] [client 10.128.202.138:48148] mod_wsgi (pid=19008): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:08.444438 2017] [wsgi:error] [pid 19008:tid 139934145226496] [client 10.128.202.138:48148] mod_wsgi (pid=19008): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:08.444481 2017] [wsgi:error] [pid 19008:tid 139934145226496] [client 10.128.202.138:48148] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:08.444519 2017] [wsgi:error] [pid 19008:tid 139934145226496] [client 10.128.202.138:48148]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:08.444578 2017] [wsgi:error] [pid 19008:tid 139934145226496] [client 10.128.202.138:48148]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:08.444621 2017] [wsgi:error] [pid 19008:tid 139934145226496] [client 10.128.202.138:48148] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:39.999118 2017] [wsgi:error] [pid 19009:tid 139934027462400] [client 10.128.202.138:48154] mod_wsgi (pid=19009): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:20:39.999172 2017] [wsgi:error] [pid 19009:tid 139934027462400] [client 10.128.202.138:48154] mod_wsgi (pid=19009): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:20:39.999219 2017] [wsgi:error] [pid 19009:tid 139934027462400] [client 10.128.202.138:48154] Traceback (most recent call last):
[Thu Nov 30 21:20:39.999267 2017] [wsgi:error] [pid 19009:tid 139934027462400] [client 10.128.202.138:48154]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:20:39.999339 2017] [wsgi:error] [pid 19009:tid 139934027462400] [client 10.128.202.138:48154]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:20:39.999381 2017] [wsgi:error] [pid 19009:tid 139934027462400] [client 10.128.202.138:48154] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:20:40.015776 2017] [wsgi:error] [pid 19010:tid 139934162028288] [client 10.128.202.138:48156] mod_wsgi (pid=19010): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:40.015826 2017] [wsgi:error] [pid 19010:tid 139934162028288] [client 10.128.202.138:48156] mod_wsgi (pid=19010): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:40.015885 2017] [wsgi:error] [pid 19010:tid 139934162028288] [client 10.128.202.138:48156] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:40.015937 2017] [wsgi:error] [pid 19010:tid 139934162028288] [client 10.128.202.138:48156]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:40.016009 2017] [wsgi:error] [pid 19010:tid 139934162028288] [client 10.128.202.138:48156]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:20:40.016048 2017] [wsgi:error] [pid 19010:tid 139934162028288] [client 10.128.202.138:48156] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:21:52.938217 2017] [wsgi:error] [pid 19008:tid 139934136825600] [client 10.128.202.138:48160] mod_wsgi (pid=19008): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:21:52.938274 2017] [wsgi:error] [pid 19008:tid 139934136825600] [client 10.128.202.138:48160] mod_wsgi (pid=19008): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:21:52.938398 2017] [wsgi:error] [pid 19008:tid 139934136825600] [client 10.128.202.138:48160] Traceback (most recent call last):
[Thu Nov 30 21:21:52.938462 2017] [wsgi:error] [pid 19008:tid 139934136825600] [client 10.128.202.138:48160]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:21:52.938546 2017] [wsgi:error] [pid 19008:tid 139934136825600] [client 10.128.202.138:48160]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:21:52.938589 2017] [wsgi:error] [pid 19008:tid 139934136825600] [client 10.128.202.138:48160] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:21:52.954551 2017] [wsgi:error] [pid 19010:tid 139934153627392] [client 10.128.202.138:48162] mod_wsgi (pid=19010): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:21:52.954602 2017] [wsgi:error] [pid 19010:tid 139934153627392] [client 10.128.202.138:48162] mod_wsgi (pid=19010): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:21:52.954641 2017] [wsgi:error] [pid 19010:tid 139934153627392] [client 10.128.202.138:48162] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:21:52.954685 2017] [wsgi:error] [pid 19010:tid 139934153627392] [client 10.128.202.138:48162]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:21:52.954747 2017] [wsgi:error] [pid 19010:tid 139934153627392] [client 10.128.202.138:48162]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:21:52.954786 2017] [wsgi:error] [pid 19010:tid 139934153627392] [client 10.128.202.138:48162] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:25:34.292266 2017] [wsgi:error] [pid 19008:tid 139934061033216] [client 10.128.202.138:48174] mod_wsgi (pid=19008): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module.
[Thu Nov 30 21:25:34.292334 2017] [wsgi:error] [pid 19008:tid 139934061033216] [client 10.128.202.138:48174] mod_wsgi (pid=19008): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'.
[Thu Nov 30 21:25:34.292381 2017] [wsgi:error] [pid 19008:tid 139934061033216] [client 10.128.202.138:48174] Traceback (most recent call last):
[Thu Nov 30 21:25:34.292428 2017] [wsgi:error] [pid 19008:tid 139934061033216] [client 10.128.202.138:48174]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>
[Thu Nov 30 21:25:34.292516 2017] [wsgi:error] [pid 19008:tid 139934061033216] [client 10.128.202.138:48174]     from django.core.wsgi import get_wsgi_application
[Thu Nov 30 21:25:34.292563 2017] [wsgi:error] [pid 19008:tid 139934061033216] [client 10.128.202.138:48174] ImportError: No module named django.core.wsgi
[Thu Nov 30 21:25:34.307482 2017] [wsgi:error] [pid 19009:tid 139934010676992] [client 10.128.202.138:48176] mod_wsgi (pid=19009): Target WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py' cannot be loaded as Python module., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:25:34.307542 2017] [wsgi:error] [pid 19009:tid 139934010676992] [client 10.128.202.138:48176] mod_wsgi (pid=19009): Exception occurred processing WSGI script '/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py'., referer: http://162.105.146.180:9048/
[Thu Nov 30 21:25:34.307588 2017] [wsgi:error] [pid 19009:tid 139934010676992] [client 10.128.202.138:48176] Traceback (most recent call last):, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:25:34.307638 2017] [wsgi:error] [pid 19009:tid 139934010676992] [client 10.128.202.138:48176]   File "/home/2017/y2017g48/apache/django/mysite/mysite/wsgi.py", line 12, in <module>, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:25:34.307708 2017] [wsgi:error] [pid 19009:tid 139934010676992] [client 10.128.202.138:48176]     from django.core.wsgi import get_wsgi_application, referer: http://162.105.146.180:9048/
[Thu Nov 30 21:25:34.307752 2017] [wsgi:error] [pid 19009:tid 139934010676992] [client 10.128.202.138:48176] ImportError: No module named django.core.wsgi, referer: http://162.105.146.180:9048/
